// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DNATest.Repositories.NguyenTQ.Models;

public partial class AppointmentLogTuTtc
{
    public int AppointmentLogTuTtcid { get; set; }

    public int? AppointmentScheduleTuTtcid { get; set; }

    public string LogText { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public string LogType { get; set; }

    public virtual AppointmentScheduleTuTtc AppointmentScheduleTuTtc { get; set; }
}