// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DNATest.Repositories.NguyenTQ.Models;

public partial class AppointmentScheduleTuTtc
{
    public int AppointmentScheduleTuTtcid { get; set; }

    public int? BookingId { get; set; }

    public int? UserAccountId { get; set; }

    public DateTime? AppointmentDate { get; set; }

    public string Status { get; set; }

    public string StaffInCharge { get; set; }

    public string Location { get; set; }

    public int? DurationMinutes { get; set; }

    public string ConfirmedBy { get; set; }

    public bool? IsConfirmed { get; set; }

    public bool? IsCanceled { get; set; }

    public string AdditionalNote { get; set; }

    public virtual ICollection<AppointmentLogTuTtc> AppointmentLogTuTtcs { get; set; } = new List<AppointmentLogTuTtc>();

    public virtual BookingMinhNdum Booking { get; set; }

    public virtual UserAccount UserAccount { get; set; }
}