// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DNATest.Repositories.NguyenTQ.Models;

public partial class BookingMinhNdum
{
    public int BookingMinhNdaid { get; set; }

    public string BookingType { get; set; }

    public string Status { get; set; }

    public decimal? TotalPrice { get; set; }

    public int? SampleCount { get; set; }

    public DateTime? RequestDate { get; set; }

    public DateTime? PreferredTime { get; set; }

    public bool? IsSelfCollection { get; set; }

    public string Note { get; set; }

    public int? UserAccountId { get; set; }

    public int? ServiceAnhThqid { get; set; }

    public virtual ICollection<AppointmentScheduleTuTtc> AppointmentScheduleTuTtcs { get; set; } = new List<AppointmentScheduleTuTtc>();

    public virtual ICollection<InvoiceMinhNdum> InvoiceMinhNda { get; set; } = new List<InvoiceMinhNdum>();

    public virtual ICollection<KitDeliveryNguyenTq> KitDeliveryNguyenTqs { get; set; } = new List<KitDeliveryNguyenTq>();

    public virtual ICollection<SampleNhanTtt> SampleNhanTtts { get; set; } = new List<SampleNhanTtt>();

    public virtual ServicesAnhThq ServiceAnhThq { get; set; }

    public virtual ICollection<TestResultThanhDc> TestResultThanhDcs { get; set; } = new List<TestResultThanhDc>();

    public virtual UserAccount UserAccount { get; set; }
}