// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DNATest.Repositories.NguyenTQ.Models;

public partial class FeedbackNguyenTq
{
    public int FeedbackId { get; set; }

    public int UserAccountId { get; set; }

    public int? KitDeliveryNguyenTqid { get; set; }

    public int? ServiceId { get; set; }

    public int? Rating { get; set; }

    public string Comment { get; set; }

    public DateTime? FeedbackDate { get; set; }

    public virtual KitDeliveryNguyenTq KitDeliveryNguyenTq { get; set; }

    public virtual UserAccount UserAccount { get; set; }
}