// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DNATest.Repositories.NguyenTQ.Models;

using System.ComponentModel.DataAnnotations;

public partial class KitDeliveryNguyenTq
{
    public int KitDeliveryNguyenTqid { get; set; }

    [Required(ErrorMessage = "Kit ID is required.")]
    public int? BookingMinhNdaid { get; set; }

    [Required(ErrorMessage = "Kit Code is required.")]
    [StringLength(50, ErrorMessage = "Kit Code cannot exceed 50 characters.")]
    public string KitCode { get; set; }

    [DataType(DataType.Date)]
    public DateTime? DeliveryDate { get; set; }

    public bool? IsDelivered { get; set; }

    public string CourierOut { get; set; }

    [StringLength(100)]
    public string TrackingNumberOut { get; set; }

    public string DeliveryStatusOut { get; set; }

    public string DeliveryNoteOut { get; set; }

    [DataType(DataType.Date)]
    public DateTime? ReturnDate { get; set; }

    public bool? IsReturned { get; set; }

    public string CourierIn { get; set; }

    public string TrackingNumberIn { get; set; }

    public string DeliveryStatusIn { get; set; }

    public string ReturnReason { get; set; }

    public string DeliveryNoteIn { get; set; }

    public bool? DamageReported { get; set; }

    [Range(0, double.MaxValue, ErrorMessage = "Fee must be a positive number.")]
    public decimal? Fee { get; set; }

    public DateTime? LastUpdated { get; set; }

    public bool? IsExpressDelivery { get; set; }

    public virtual BookingMinhNdum BookingMinhNda { get; set; }

    public virtual ICollection<FeedbackNguyenTq> FeedbackNguyenTqs { get; set; } = new List<FeedbackNguyenTq>();
}
