// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DNATest.Repositories.NguyenTQ.Models;

public partial class RelationshipTestThanhDc
{
    public int RelationshipTestThanhDcid { get; set; }

    public int TestResultThanhDcid { get; set; }

    public string RelationshipExpected { get; set; }

    public string RelationshipConclusion { get; set; }

    public decimal? MatchProbability { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual TestResultThanhDc TestResultThanhDc { get; set; }
}