// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DNATest.Repositories.NguyenTQ.Models;

public partial class SampleNhanTtt
{
    public int SampleNhanTttid { get; set; }

    public int? BookingMinhNdaid { get; set; }

    public string SampleCode { get; set; }

    public string CollectedBy { get; set; }

    public int? Quantity { get; set; }

    public DateTime? CollectedDate { get; set; }

    public DateTime? ReceivedDate { get; set; }

    public bool? IsValid { get; set; }

    public bool? IsReferenceSample { get; set; }

    public string Note { get; set; }

    public string Status { get; set; }

    public virtual BookingMinhNdum BookingMinhNda { get; set; }

    public virtual ICollection<SampleTestResultNhanTtt> SampleTestResultNhanTtts { get; set; } = new List<SampleTestResultNhanTtt>();
}