// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DNATest.Repositories.NguyenTQ.Models;

public partial class ServicesAnhThq
{
    public int ServiceAnhThqid { get; set; }

    public string ServiceName { get; set; }

    public string ServiceType { get; set; }

    public string Description { get; set; }

    public string Category { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<BookingMinhNdum> BookingMinhNda { get; set; } = new List<BookingMinhNdum>();

    public virtual ICollection<ServicePriceListAnhThq> ServicePriceListAnhThqs { get; set; } = new List<ServicePriceListAnhThq>();
}